apiVersion: v1
kind: Service
metadata:
  namespace: nita
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml -v
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: proxy
  name: proxy
spec:
  ports:
    - name: "9443"
      port: 9443
      targetPort: 9443
  selector:
    io.kompose.service: proxy
status:
  loadBalancer: {}
