apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: modify-pods-to-sa
subjects:
  - kind: ServiceAccount
    name: internal-jenknis-pod
roleRef:
  kind: Role
  name: modify-pods
  apiGroup: rbac.authorization.k8s.io
root@ubuntu20-04:~# cat service-account.yaml 
apiVersion: v1
kind: ServiceAccount
metadata:
  name: internal-jenknis-pod
